//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVISC_EdiTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOptions1
    {
        public int idOption { get; set; }
        public string Titol { get; set; }
        public string Descripcio { get; set; }
        public string Classe { get; set; }
        public string Form { get; set; }
        public Nullable<int> NivellAcces { get; set; }
        public string Categoria { get; set; }
        public byte[] Icon { get; set; }
    }
}
