//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVISC_EdiTools
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRanksBackup
    {
        public int idUserRank { get; set; }
        public string CodeUserRank { get; set; }
        public string DescUserRank { get; set; }
    }
}
