//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVISC_DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuOptions
    {
        public int idApp { get; set; }
        public string Ensamblat { get; set; }
        public string Classe { get; set; }
        public string Nom { get; set; }
        public string Descripcio { get; set; }
        public byte[] Imatge { get; set; }
        public int accesLvlReq { get; set; }
    }
}
