//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVISC_DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersOptions
    {
        public int idUser { get; set; }
        public string Classe { get; set; }
        public string Descripcion { get; set; }
        public string Form { get; set; }
        public string Imatges { get; set; }
        public Nullable<int> accesReqerit { get; set; }
    }
}
